<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SuccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuccesRepository extends EntityRepository
{
}
