frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

user_dashboard:
    path:     /user/dashboard
    defaults: { _controller: FrontendBundle:Info:Dashboard }

new_actu:
    path:     /user/new/actu
    defaults: { _controller: FrontendBundle:Info:newActu }

index_challenge:
    path:     /challenge
    defaults: { _controller: FrontendBundle:Default:challenge }

challenge_new:
    path:     /challenge/new
    defaults: { _controller: FrontendBundle:Default:addChallenge }
