frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

user_dashboard:
    path:     /user/dashboard
    defaults: { _controller: FrontendBundle:Info:Dashboard }
